### ISSUE TITLE
Rezeptesuche nach Zutaten

### ISSUE THREAD

**Issue by david-jointech** [EorlBruder/ris2.0#25]

**Comment by decay42** [comment]
Brainstorming:
- neue Suchleiste oben oder neue Seite?
- Zutaten mit Komma getrennt in einem Suchfeld (einfacher: ein Suchfeld mit Autocomplete, ein zweites Feld in dem das jeweils ausgewählte landet, mit dem x zum wieder löschen)
- weitere Suchkriteren oder nur Zutaten?
- UND/ODER Setting, also ALLE Zutaten oder EINE DER Zutaten?

**Comment by decay42** [comment]
Kann auf http://127.0.0.1:8000/rezeptzutatensuche/ getestet werden. Momentan wird für jede Zutat ein Rezept gesucht, nicht ein Rezept, das alle Zutaten hat.
